name: Run Consuming Services example

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Ballerina Build
        uses: ballerina-platform/ballerina-action@master
        with:
          args:
            build consuming_services.bal
        env:
          WORKING_DIR: "src/scripts"
